# PeaksolEssUpdater运行于PeaksolEss.
command /peu:
	aliases: /peupdate
	usage: /peu
	description: 更新 PeaksolEss
	permission: peaksoless.admin
	trigger:
		broadcast "&a正在更新PeaksolEss, 服务器可能会暂时无响应..."
		wait 0.5 second
		download from "https://peaksol.coding.me/PeaksolEss/PeaksolEss.sk" to "plugins/Skript/scripts/PeaksolEss.sk"
		wait 0.5 second
		broadcast "&a更新完成. 正在重载PeaksolEss..."
		wait 0.5 second
		make player execute command "sk reload PeaksolEss"